### ISSUE TITLE
Headshot overlaps with headline when there's no standfirst

### ISSUE THREAD

**Issue by robsquires** [Financial-Times/o-topper#23]
## What
When a stand first isn't present, the headshot overlaps with the topper headline. It's not clear from the logic in `next-article` if this is actually possible.

## Details
<img width="387" alt="screenshot 2018-12-10 at 11 16 06" src="https://user-images.githubusercontent.com/616321/49729823-7a1b1f00-fc6e-11e8-9d5e-f9479351992e.png">

**Comment by chee** [comment]
there are plenty of our components that break if you don't follow the markup. the markup in the docs and demos always has a standfirst for those types of toppers (i.e., normal toppers. not special things like live blog package)

it doesn't appear to happen in production, or else we'd have had another report since 2018

so i'm going to close this. if it's a problem in the future, we can investigate it then.

**Comment by chee** [comment]
re-opening this minutes later because @apaleslimghost has pointed out the article has [logic](https://github.com/Financial-Times/next-article/blob/master/pages/topper/components/intro.jsx#L8-L12) for an empty standfirst
